version: "2.2"
services:
  hub:
    image: selenium/hub
    ports:
      - 4444:4444
    environment:
      GRID_MAX_SESSION: 10
  firefox:
    image: selenium/node-firefox
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      NODE_MAX_INSTANCES: 1
      NODE_MAX_SESSION: 1
  chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
      NODE_MAX_INSTANCES: 1
      NODE_MAX_SESSION: 1
  ngnix:
    image: oglcnarbc/myngnix:1.0
    ports:
      - "8001:80"