ngnixreport:
  image: nginx:alpine
  ports:
    - "82:80"
  volumes:
    - ./:/var/www
    - ./nginx/conf.d/:/etc/nginx/conf.d/
hub:
  image: selenium/hub
  ports:
    - "4444:4444"
firefox:
  image: selenium/node-firefox:3.5
  environment:
    - NODE_MAX_INSTANCE=1
    - NODE_MAX_SESSION=1
  links:
  - hub
chrome:
  image: selenium/node-chrome:3.5
  environment:
    - NODE_MAX_INSTANCE=1
    - NODE_MAX_SESSION=1
  links:
  - hub