web_server:
  image: bilalmitaf/mynginx:0.1
  ports:
    - "8001:80"
hub:
  image: selenium/hub
  ports:
    - "4444:4444"
firefox:
  image: selenium/node-firefox:3.5
  environment:
    - NODE_MAX_INSTANCE=10
    - NODE_MAX_SESSION=10
  links:
  - hub
chrome:
  image: selenium/node-chrome:3.5
  environment:
    - NODE_MAX_INSTANCE=10
    - NODE_MAX_SESSION=10
  links:
  - hub